name: 'Check AWS Service Health'
description: 'A GitHub Action to check the health status of specified AWS services.'

inputs:
  services:
    description: 'Comma-separated list of AWS services to check.'
    required: true
  aws-region:
    description: 'AWS region to check the health status of the services.'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID.'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key.'
    required: true
    
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3
      shell: bash
        
    - name: Run Script
      run: python src/check_aws_services.py ${{ inputs.services }}
      shell: bash
      env:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
