name: Check AWS Services Health
on: [push]
jobs:
  check_services:
    runs-on: ubuntu-latest
    steps:
      - name: Check AWS Service Health
        uses: getcacheflow/check-aws-service-health@v0.1.4
        with:
          services: 'Amazon S3,Amazon RDS'
          aws-region: 'us-east-2'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
